// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tool

import "strconv"

type BuiltinToolID uint16

const (
	BuiltinToolIDInvalid              BuiltinToolID = 0
	BuiltinToolIDDatetime             BuiltinToolID = 1
	BuiltinToolIDSleep                BuiltinToolID = 2
	BuiltinToolIDSearchContactEmail   BuiltinToolID = 3
	BuiltinToolIDListOpenEmails       BuiltinToolID = 4
	BuiltinToolIDComposeEmail         BuiltinToolID = 5
	BuiltinToolIDSendEmailDraftWindow BuiltinToolID = 6
	BuiltinToolIDMouseRightClick      BuiltinToolID = 7
	BuiltinToolIDMouseLeftClick       BuiltinToolID = 8
	BuiltinToolIDPhoneCall            BuiltinToolID = 9
	BuiltinToolIDFullScreenshot       BuiltinToolID = 10
	BuiltinToolIDOpenURL              BuiltinToolID = 11
	BuiltinToolIDScrollDown           BuiltinToolID = 12
	BuiltinToolIDScrollUp             BuiltinToolID = 13
	BuiltinToolIDPageDown             BuiltinToolID = 14
	BuiltinToolIDPageUp               BuiltinToolID = 15
	BuiltinToolIDWebScreenshot        BuiltinToolID = 16
	BuiltinToolIDMax                  BuiltinToolID = 17
)

var EnumNamesBuiltinToolID = map[BuiltinToolID]string{
	BuiltinToolIDInvalid:              "Invalid",
	BuiltinToolIDDatetime:             "Datetime",
	BuiltinToolIDSleep:                "Sleep",
	BuiltinToolIDSearchContactEmail:   "SearchContactEmail",
	BuiltinToolIDListOpenEmails:       "ListOpenEmails",
	BuiltinToolIDComposeEmail:         "ComposeEmail",
	BuiltinToolIDSendEmailDraftWindow: "SendEmailDraftWindow",
	BuiltinToolIDMouseRightClick:      "MouseRightClick",
	BuiltinToolIDMouseLeftClick:       "MouseLeftClick",
	BuiltinToolIDPhoneCall:            "PhoneCall",
	BuiltinToolIDFullScreenshot:       "FullScreenshot",
	BuiltinToolIDOpenURL:              "OpenURL",
	BuiltinToolIDScrollDown:           "ScrollDown",
	BuiltinToolIDScrollUp:             "ScrollUp",
	BuiltinToolIDPageDown:             "PageDown",
	BuiltinToolIDPageUp:               "PageUp",
	BuiltinToolIDWebScreenshot:        "WebScreenshot",
	BuiltinToolIDMax:                  "Max",
}

var EnumValuesBuiltinToolID = map[string]BuiltinToolID{
	"Invalid":              BuiltinToolIDInvalid,
	"Datetime":             BuiltinToolIDDatetime,
	"Sleep":                BuiltinToolIDSleep,
	"SearchContactEmail":   BuiltinToolIDSearchContactEmail,
	"ListOpenEmails":       BuiltinToolIDListOpenEmails,
	"ComposeEmail":         BuiltinToolIDComposeEmail,
	"SendEmailDraftWindow": BuiltinToolIDSendEmailDraftWindow,
	"MouseRightClick":      BuiltinToolIDMouseRightClick,
	"MouseLeftClick":       BuiltinToolIDMouseLeftClick,
	"PhoneCall":            BuiltinToolIDPhoneCall,
	"FullScreenshot":       BuiltinToolIDFullScreenshot,
	"OpenURL":              BuiltinToolIDOpenURL,
	"ScrollDown":           BuiltinToolIDScrollDown,
	"ScrollUp":             BuiltinToolIDScrollUp,
	"PageDown":             BuiltinToolIDPageDown,
	"PageUp":               BuiltinToolIDPageUp,
	"WebScreenshot":        BuiltinToolIDWebScreenshot,
	"Max":                  BuiltinToolIDMax,
}

func (v BuiltinToolID) String() string {
	if s, ok := EnumNamesBuiltinToolID[v]; ok {
		return s
	}
	return "BuiltinToolID(" + strconv.FormatInt(int64(v), 10) + ")"
}
