// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tool

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type BuiltinToolInfo struct {
	_tab flatbuffers.Table
}

func GetRootAsBuiltinToolInfo(buf []byte, offset flatbuffers.UOffsetT) *BuiltinToolInfo {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BuiltinToolInfo{}
	x.Init(buf, n+offset)
	return x
}

func FinishBuiltinToolInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsBuiltinToolInfo(buf []byte, offset flatbuffers.UOffsetT) *BuiltinToolInfo {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &BuiltinToolInfo{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedBuiltinToolInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *BuiltinToolInfo) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BuiltinToolInfo) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BuiltinToolInfo) ToolId() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BuiltinToolInfo) MutateToolId(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func BuiltinToolInfoStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func BuiltinToolInfoAddToolId(builder *flatbuffers.Builder, toolId uint16) {
	builder.PrependUint16Slot(0, toolId, 0)
}
func BuiltinToolInfoEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
