// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tool

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type InternalToolCreateResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsInternalToolCreateResponse(buf []byte, offset flatbuffers.UOffsetT) *InternalToolCreateResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &InternalToolCreateResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishInternalToolCreateResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsInternalToolCreateResponse(buf []byte, offset flatbuffers.UOffsetT) *InternalToolCreateResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &InternalToolCreateResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedInternalToolCreateResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *InternalToolCreateResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *InternalToolCreateResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *InternalToolCreateResponse) ToolId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *InternalToolCreateResponse) MutateToolId(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func InternalToolCreateResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func InternalToolCreateResponseAddToolId(builder *flatbuffers.Builder, toolId int64) {
	builder.PrependInt64Slot(0, toolId, 0)
}
func InternalToolCreateResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
