// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tool

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type InternalToolInfo struct {
	_tab flatbuffers.Table
}

func GetRootAsInternalToolInfo(buf []byte, offset flatbuffers.UOffsetT) *InternalToolInfo {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &InternalToolInfo{}
	x.Init(buf, n+offset)
	return x
}

func FinishInternalToolInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsInternalToolInfo(buf []byte, offset flatbuffers.UOffsetT) *InternalToolInfo {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &InternalToolInfo{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedInternalToolInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *InternalToolInfo) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *InternalToolInfo) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *InternalToolInfo) ToolId() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *InternalToolInfo) MutateToolId(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func InternalToolInfoStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func InternalToolInfoAddToolId(builder *flatbuffers.Builder, toolId uint16) {
	builder.PrependUint16Slot(0, toolId, 0)
}
func InternalToolInfoEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
