// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tool

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type InternalToolCreateParamSpec struct {
	_tab flatbuffers.Table
}

func GetRootAsInternalToolCreateParamSpec(buf []byte, offset flatbuffers.UOffsetT) *InternalToolCreateParamSpec {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &InternalToolCreateParamSpec{}
	x.Init(buf, n+offset)
	return x
}

func FinishInternalToolCreateParamSpecBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsInternalToolCreateParamSpec(buf []byte, offset flatbuffers.UOffsetT) *InternalToolCreateParamSpec {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &InternalToolCreateParamSpec{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedInternalToolCreateParamSpecBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *InternalToolCreateParamSpec) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *InternalToolCreateParamSpec) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *InternalToolCreateParamSpec) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *InternalToolCreateParamSpec) Description() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *InternalToolCreateParamSpec) Type() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *InternalToolCreateParamSpec) Required() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *InternalToolCreateParamSpec) MutateRequired(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

func InternalToolCreateParamSpecStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func InternalToolCreateParamSpecAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func InternalToolCreateParamSpecAddDescription(builder *flatbuffers.Builder, description flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(description), 0)
}
func InternalToolCreateParamSpecAddType(builder *flatbuffers.Builder, type_ flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(type_), 0)
}
func InternalToolCreateParamSpecAddRequired(builder *flatbuffers.Builder, required bool) {
	builder.PrependBoolSlot(3, required, false)
}
func InternalToolCreateParamSpecEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
