// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tool

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type NormalToolInfo struct {
	_tab flatbuffers.Table
}

func GetRootAsNormalToolInfo(buf []byte, offset flatbuffers.UOffsetT) *NormalToolInfo {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &NormalToolInfo{}
	x.Init(buf, n+offset)
	return x
}

func FinishNormalToolInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsNormalToolInfo(buf []byte, offset flatbuffers.UOffsetT) *NormalToolInfo {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &NormalToolInfo{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedNormalToolInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *NormalToolInfo) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *NormalToolInfo) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *NormalToolInfo) WorkloadId(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *NormalToolInfo) WorkloadIdLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *NormalToolInfo) WorkloadIdBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *NormalToolInfo) MutateWorkloadId(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *NormalToolInfo) ToolId() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *NormalToolInfo) MutateToolId(n uint16) bool {
	return rcv._tab.MutateUint16Slot(6, n)
}

func NormalToolInfoStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func NormalToolInfoAddWorkloadId(builder *flatbuffers.Builder, workloadId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(workloadId), 0)
}
func NormalToolInfoStartWorkloadIdVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func NormalToolInfoAddToolId(builder *flatbuffers.Builder, toolId uint16) {
	builder.PrependUint16Slot(1, toolId, 0)
}
func NormalToolInfoEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
