// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tool

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Param struct {
	_tab flatbuffers.Table
}

func GetRootAsParam(buf []byte, offset flatbuffers.UOffsetT) *Param {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Param{}
	x.Init(buf, n+offset)
	return x
}

func FinishParamBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsParam(buf []byte, offset flatbuffers.UOffsetT) *Param {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Param{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedParamBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Param) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Param) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Param) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Param) Value() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ParamStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ParamAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(key), 0)
}
func ParamAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(value), 0)
}
func ParamEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
