// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tool

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ToolInvocationRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsToolInvocationRequest(buf []byte, offset flatbuffers.UOffsetT) *ToolInvocationRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ToolInvocationRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishToolInvocationRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsToolInvocationRequest(buf []byte, offset flatbuffers.UOffsetT) *ToolInvocationRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ToolInvocationRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedToolInvocationRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ToolInvocationRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ToolInvocationRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ToolInvocationRequest) ToolInfoType() ToolInfo {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return ToolInfo(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ToolInvocationRequest) MutateToolInfoType(n ToolInfo) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *ToolInvocationRequest) ToolInfo(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func (rcv *ToolInvocationRequest) ToolName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ToolInvocationRequest) Params(obj *Param, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *ToolInvocationRequest) ParamsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func ToolInvocationRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func ToolInvocationRequestAddToolInfoType(builder *flatbuffers.Builder, toolInfoType ToolInfo) {
	builder.PrependByteSlot(0, byte(toolInfoType), 0)
}
func ToolInvocationRequestAddToolInfo(builder *flatbuffers.Builder, toolInfo flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(toolInfo), 0)
}
func ToolInvocationRequestAddToolName(builder *flatbuffers.Builder, toolName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(toolName), 0)
}
func ToolInvocationRequestAddParams(builder *flatbuffers.Builder, params flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(params), 0)
}
func ToolInvocationRequestStartParamsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ToolInvocationRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
