// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tool

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ToolInvocationResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsToolInvocationResponse(buf []byte, offset flatbuffers.UOffsetT) *ToolInvocationResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ToolInvocationResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishToolInvocationResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsToolInvocationResponse(buf []byte, offset flatbuffers.UOffsetT) *ToolInvocationResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ToolInvocationResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedToolInvocationResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ToolInvocationResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ToolInvocationResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ToolInvocationResponse) Result() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ToolInvocationResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ToolInvocationResponseAddResult(builder *flatbuffers.Builder, result flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(result), 0)
}
func ToolInvocationResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
