// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tool

import "strconv"

type ToolInfo byte

const (
	ToolInfoNONE             ToolInfo = 0
	ToolInfoBuiltinToolInfo  ToolInfo = 1
	ToolInfoNormalToolInfo   ToolInfo = 2
	ToolInfoInternalToolInfo ToolInfo = 3
)

var EnumNamesToolInfo = map[ToolInfo]string{
	ToolInfoNONE:             "NONE",
	ToolInfoBuiltinToolInfo:  "BuiltinToolInfo",
	ToolInfoNormalToolInfo:   "NormalToolInfo",
	ToolInfoInternalToolInfo: "InternalToolInfo",
}

var EnumValuesToolInfo = map[string]ToolInfo{
	"NONE":             ToolInfoNONE,
	"BuiltinToolInfo":  ToolInfoBuiltinToolInfo,
	"NormalToolInfo":   ToolInfoNormalToolInfo,
	"InternalToolInfo": ToolInfoInternalToolInfo,
}

func (v ToolInfo) String() string {
	if s, ok := EnumNamesToolInfo[v]; ok {
		return s
	}
	return "ToolInfo(" + strconv.FormatInt(int64(v), 10) + ")"
}
