// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package transform

import "strconv"

type TransformRequest_Params byte

const (
	TransformRequest_ParamsNONE                                   TransformRequest_Params = 0
	TransformRequest_Paramsspear_proto_chat_ChatCompletionRequest TransformRequest_Params = 1
	TransformRequest_Paramsspear_proto_speech_ASRRequest          TransformRequest_Params = 2
	TransformRequest_ParamsTranformRequest_ParamsRaw              TransformRequest_Params = 3
)

var EnumNamesTransformRequest_Params = map[TransformRequest_Params]string{
	TransformRequest_ParamsNONE:                                   "NONE",
	TransformRequest_Paramsspear_proto_chat_ChatCompletionRequest: "spear_proto_chat_ChatCompletionRequest",
	TransformRequest_Paramsspear_proto_speech_ASRRequest:          "spear_proto_speech_ASRRequest",
	TransformRequest_ParamsTranformRequest_ParamsRaw:              "TranformRequest_ParamsRaw",
}

var EnumValuesTransformRequest_Params = map[string]TransformRequest_Params{
	"NONE":                                   TransformRequest_ParamsNONE,
	"spear_proto_chat_ChatCompletionRequest": TransformRequest_Paramsspear_proto_chat_ChatCompletionRequest,
	"spear_proto_speech_ASRRequest":          TransformRequest_Paramsspear_proto_speech_ASRRequest,
	"TranformRequest_ParamsRaw":              TransformRequest_ParamsTranformRequest_ParamsRaw,
}

func (v TransformRequest_Params) String() string {
	if s, ok := EnumNamesTransformRequest_Params[v]; ok {
		return s
	}
	return "TransformRequest_Params(" + strconv.FormatInt(int64(v), 10) + ")"
}
