// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package transform

import "strconv"

type TransformOperation int32

const (
	TransformOperationLLM          TransformOperation = 0
	TransformOperationTools        TransformOperation = 1
	TransformOperationEmbeddings   TransformOperation = 2
	TransformOperationOCR          TransformOperation = 3
	TransformOperationTextToSpeech TransformOperation = 4
	TransformOperationASR          TransformOperation = 5
	TransformOperationTextToImage  TransformOperation = 6
)

var EnumNamesTransformOperation = map[TransformOperation]string{
	TransformOperationLLM:          "LLM",
	TransformOperationTools:        "Tools",
	TransformOperationEmbeddings:   "Embeddings",
	TransformOperationOCR:          "OCR",
	TransformOperationTextToSpeech: "TextToSpeech",
	TransformOperationASR:          "ASR",
	TransformOperationTextToImage:  "TextToImage",
}

var EnumValuesTransformOperation = map[string]TransformOperation{
	"LLM":          TransformOperationLLM,
	"Tools":        TransformOperationTools,
	"Embeddings":   TransformOperationEmbeddings,
	"OCR":          TransformOperationOCR,
	"TextToSpeech": TransformOperationTextToSpeech,
	"ASR":          TransformOperationASR,
	"TextToImage":  TransformOperationTextToImage,
}

func (v TransformOperation) String() string {
	if s, ok := EnumNamesTransformOperation[v]; ok {
		return s
	}
	return "TransformOperation(" + strconv.FormatInt(int64(v), 10) + ")"
}
