// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package transform

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TransformResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsTransformResponse(buf []byte, offset flatbuffers.UOffsetT) *TransformResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TransformResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishTransformResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTransformResponse(buf []byte, offset flatbuffers.UOffsetT) *TransformResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TransformResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTransformResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TransformResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TransformResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TransformResponse) DataType() TransformResponse_Data {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return TransformResponse_Data(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *TransformResponse) MutateDataType(n TransformResponse_Data) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *TransformResponse) Data(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func TransformResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func TransformResponseAddDataType(builder *flatbuffers.Builder, dataType TransformResponse_Data) {
	builder.PrependByteSlot(0, byte(dataType), 0)
}
func TransformResponseAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(data), 0)
}
func TransformResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
