// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package transform

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TranformResponse_DataRaw struct {
	_tab flatbuffers.Table
}

func GetRootAsTranformResponse_DataRaw(buf []byte, offset flatbuffers.UOffsetT) *TranformResponse_DataRaw {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TranformResponse_DataRaw{}
	x.Init(buf, n+offset)
	return x
}

func FinishTranformResponse_DataRawBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTranformResponse_DataRaw(buf []byte, offset flatbuffers.UOffsetT) *TranformResponse_DataRaw {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TranformResponse_DataRaw{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTranformResponse_DataRawBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TranformResponse_DataRaw) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TranformResponse_DataRaw) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TranformResponse_DataRaw) Data() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func TranformResponse_DataRawStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func TranformResponse_DataRawAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(data), 0)
}
func TranformResponse_DataRawEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
