// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package transform

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TranformRequest_ParamsRaw struct {
	_tab flatbuffers.Table
}

func GetRootAsTranformRequest_ParamsRaw(buf []byte, offset flatbuffers.UOffsetT) *TranformRequest_ParamsRaw {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TranformRequest_ParamsRaw{}
	x.Init(buf, n+offset)
	return x
}

func FinishTranformRequest_ParamsRawBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTranformRequest_ParamsRaw(buf []byte, offset flatbuffers.UOffsetT) *TranformRequest_ParamsRaw {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TranformRequest_ParamsRaw{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTranformRequest_ParamsRawBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TranformRequest_ParamsRaw) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TranformRequest_ParamsRaw) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TranformRequest_ParamsRaw) Data() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TranformRequest_ParamsRaw) More() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *TranformRequest_ParamsRaw) MutateMore(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func TranformRequest_ParamsRawStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func TranformRequest_ParamsRawAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(data), 0)
}
func TranformRequest_ParamsRawAddMore(builder *flatbuffers.Builder, more bool) {
	builder.PrependBoolSlot(1, more, false)
}
func TranformRequest_ParamsRawEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
