// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package transform

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TransformRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsTransformRequest(buf []byte, offset flatbuffers.UOffsetT) *TransformRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TransformRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishTransformRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTransformRequest(buf []byte, offset flatbuffers.UOffsetT) *TransformRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TransformRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTransformRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TransformRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TransformRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TransformRequest) InputTypes(j int) TransformType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return TransformType(rcv._tab.GetInt32(a + flatbuffers.UOffsetT(j*4)))
	}
	return 0
}

func (rcv *TransformRequest) InputTypesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *TransformRequest) MutateInputTypes(j int, n TransformType) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateInt32(a+flatbuffers.UOffsetT(j*4), int32(n))
	}
	return false
}

func (rcv *TransformRequest) OutputTypes(j int) TransformType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return TransformType(rcv._tab.GetInt32(a + flatbuffers.UOffsetT(j*4)))
	}
	return 0
}

func (rcv *TransformRequest) OutputTypesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *TransformRequest) MutateOutputTypes(j int, n TransformType) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateInt32(a+flatbuffers.UOffsetT(j*4), int32(n))
	}
	return false
}

func (rcv *TransformRequest) Operations(j int) TransformOperation {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return TransformOperation(rcv._tab.GetInt32(a + flatbuffers.UOffsetT(j*4)))
	}
	return 0
}

func (rcv *TransformRequest) OperationsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *TransformRequest) MutateOperations(j int, n TransformOperation) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateInt32(a+flatbuffers.UOffsetT(j*4), int32(n))
	}
	return false
}

func (rcv *TransformRequest) ParamsType() TransformRequest_Params {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return TransformRequest_Params(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *TransformRequest) MutateParamsType(n TransformRequest_Params) bool {
	return rcv._tab.MutateByteSlot(10, byte(n))
}

func (rcv *TransformRequest) Params(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func TransformRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func TransformRequestAddInputTypes(builder *flatbuffers.Builder, inputTypes flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(inputTypes), 0)
}
func TransformRequestStartInputTypesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func TransformRequestAddOutputTypes(builder *flatbuffers.Builder, outputTypes flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(outputTypes), 0)
}
func TransformRequestStartOutputTypesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func TransformRequestAddOperations(builder *flatbuffers.Builder, operations flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(operations), 0)
}
func TransformRequestStartOperationsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func TransformRequestAddParamsType(builder *flatbuffers.Builder, paramsType TransformRequest_Params) {
	builder.PrependByteSlot(3, byte(paramsType), 0)
}
func TransformRequestAddParams(builder *flatbuffers.Builder, params flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(params), 0)
}
func TransformRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
