// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package transform

import "strconv"

type TransformType int32

const (
	TransformTypeImage   TransformType = 0
	TransformTypeText    TransformType = 1
	TransformTypeAudio   TransformType = 2
	TransformTypeVideo   TransformType = 3
	TransformTypeTensor  TransformType = 4
	TransformTypeVector  TransformType = 5
	TransformTypeUnknown TransformType = 6
)

var EnumNamesTransformType = map[TransformType]string{
	TransformTypeImage:   "Image",
	TransformTypeText:    "Text",
	TransformTypeAudio:   "Audio",
	TransformTypeVideo:   "Video",
	TransformTypeTensor:  "Tensor",
	TransformTypeVector:  "Vector",
	TransformTypeUnknown: "Unknown",
}

var EnumValuesTransformType = map[string]TransformType{
	"Image":   TransformTypeImage,
	"Text":    TransformTypeText,
	"Audio":   TransformTypeAudio,
	"Video":   TransformTypeVideo,
	"Tensor":  TransformTypeTensor,
	"Vector":  TransformTypeVector,
	"Unknown": TransformTypeUnknown,
}

func (v TransformType) String() string {
	if s, ok := EnumNamesTransformType[v]; ok {
		return s
	}
	return "TransformType(" + strconv.FormatInt(int64(v), 10) + ")"
}
