// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package transform

import "strconv"

type TransformResponse_Data byte

const (
	TransformResponse_DataNONE                                    TransformResponse_Data = 0
	TransformResponse_Dataspear_proto_chat_ChatCompletionResponse TransformResponse_Data = 1
	TransformResponse_Dataspear_proto_speech_ASRResponse          TransformResponse_Data = 2
	TransformResponse_DataTranformResponse_DataRaw                TransformResponse_Data = 3
)

var EnumNamesTransformResponse_Data = map[TransformResponse_Data]string{
	TransformResponse_DataNONE:                                    "NONE",
	TransformResponse_Dataspear_proto_chat_ChatCompletionResponse: "spear_proto_chat_ChatCompletionResponse",
	TransformResponse_Dataspear_proto_speech_ASRResponse:          "spear_proto_speech_ASRResponse",
	TransformResponse_DataTranformResponse_DataRaw:                "TranformResponse_DataRaw",
}

var EnumValuesTransformResponse_Data = map[string]TransformResponse_Data{
	"NONE":                                    TransformResponse_DataNONE,
	"spear_proto_chat_ChatCompletionResponse": TransformResponse_Dataspear_proto_chat_ChatCompletionResponse,
	"spear_proto_speech_ASRResponse":          TransformResponse_Dataspear_proto_speech_ASRResponse,
	"TranformResponse_DataRaw":                TransformResponse_DataTranformResponse_DataRaw,
}

func (v TransformResponse_Data) String() string {
	if s, ok := EnumNamesTransformResponse_Data[v]; ok {
		return s
	}
	return "TransformResponse_Data(" + strconv.FormatInt(int64(v), 10) + ")"
}
