// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package stream

import "strconv"

type NotificationEventType byte

const (
	NotificationEventTypeError      NotificationEventType = 0
	NotificationEventTypeConfigured NotificationEventType = 1
	NotificationEventTypeCreated    NotificationEventType = 2
	NotificationEventTypeUpdated    NotificationEventType = 3
	NotificationEventTypeDeleted    NotificationEventType = 4
	NotificationEventTypeCompleted  NotificationEventType = 5
	NotificationEventTypeCancelled  NotificationEventType = 6
)

var EnumNamesNotificationEventType = map[NotificationEventType]string{
	NotificationEventTypeError:      "Error",
	NotificationEventTypeConfigured: "Configured",
	NotificationEventTypeCreated:    "Created",
	NotificationEventTypeUpdated:    "Updated",
	NotificationEventTypeDeleted:    "Deleted",
	NotificationEventTypeCompleted:  "Completed",
	NotificationEventTypeCancelled:  "Cancelled",
}

var EnumValuesNotificationEventType = map[string]NotificationEventType{
	"Error":      NotificationEventTypeError,
	"Configured": NotificationEventTypeConfigured,
	"Created":    NotificationEventTypeCreated,
	"Updated":    NotificationEventTypeUpdated,
	"Deleted":    NotificationEventTypeDeleted,
	"Completed":  NotificationEventTypeCompleted,
	"Cancelled":  NotificationEventTypeCancelled,
}

func (v NotificationEventType) String() string {
	if s, ok := EnumNamesNotificationEventType[v]; ok {
		return s
	}
	return "NotificationEventType(" + strconv.FormatInt(int64(v), 10) + ")"
}
