// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package stream

import "strconv"

type OperationType byte

const (
	OperationTypeNoOp      OperationType = 0
	OperationTypeConfigure OperationType = 1
	OperationTypeCreate    OperationType = 2
	OperationTypePatch     OperationType = 3
	OperationTypeDelete    OperationType = 4
	OperationTypeAppend    OperationType = 5
	OperationTypeTruncate  OperationType = 6
	OperationTypeCancel    OperationType = 7
)

var EnumNamesOperationType = map[OperationType]string{
	OperationTypeNoOp:      "NoOp",
	OperationTypeConfigure: "Configure",
	OperationTypeCreate:    "Create",
	OperationTypePatch:     "Patch",
	OperationTypeDelete:    "Delete",
	OperationTypeAppend:    "Append",
	OperationTypeTruncate:  "Truncate",
	OperationTypeCancel:    "Cancel",
}

var EnumValuesOperationType = map[string]OperationType{
	"NoOp":      OperationTypeNoOp,
	"Configure": OperationTypeConfigure,
	"Create":    OperationTypeCreate,
	"Patch":     OperationTypePatch,
	"Delete":    OperationTypeDelete,
	"Append":    OperationTypeAppend,
	"Truncate":  OperationTypeTruncate,
	"Cancel":    OperationTypeCancel,
}

func (v OperationType) String() string {
	if s, ok := EnumNamesOperationType[v]; ok {
		return s
	}
	return "OperationType(" + strconv.FormatInt(int64(v), 10) + ")"
}
