// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package stream

import "strconv"

type StreamDataWrapper byte

const (
	StreamDataWrapperNONE                    StreamDataWrapper = 0
	StreamDataWrapperStreamOperationEvent    StreamDataWrapper = 1
	StreamDataWrapperStreamNotificationEvent StreamDataWrapper = 2
	StreamDataWrapperStreamRawData           StreamDataWrapper = 3
)

var EnumNamesStreamDataWrapper = map[StreamDataWrapper]string{
	StreamDataWrapperNONE:                    "NONE",
	StreamDataWrapperStreamOperationEvent:    "StreamOperationEvent",
	StreamDataWrapperStreamNotificationEvent: "StreamNotificationEvent",
	StreamDataWrapperStreamRawData:           "StreamRawData",
}

var EnumValuesStreamDataWrapper = map[string]StreamDataWrapper{
	"NONE":                    StreamDataWrapperNONE,
	"StreamOperationEvent":    StreamDataWrapperStreamOperationEvent,
	"StreamNotificationEvent": StreamDataWrapperStreamNotificationEvent,
	"StreamRawData":           StreamDataWrapperStreamRawData,
}

func (v StreamDataWrapper) String() string {
	if s, ok := EnumNamesStreamDataWrapper[v]; ok {
		return s
	}
	return "StreamDataWrapper(" + strconv.FormatInt(int64(v), 10) + ")"
}
