// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package stream

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StreamNotificationEvent struct {
	_tab flatbuffers.Table
}

func GetRootAsStreamNotificationEvent(buf []byte, offset flatbuffers.UOffsetT) *StreamNotificationEvent {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StreamNotificationEvent{}
	x.Init(buf, n+offset)
	return x
}

func FinishStreamNotificationEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStreamNotificationEvent(buf []byte, offset flatbuffers.UOffsetT) *StreamNotificationEvent {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StreamNotificationEvent{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStreamNotificationEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StreamNotificationEvent) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StreamNotificationEvent) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StreamNotificationEvent) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StreamNotificationEvent) Type() NotificationEventType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return NotificationEventType(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *StreamNotificationEvent) MutateType(n NotificationEventType) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *StreamNotificationEvent) Length() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StreamNotificationEvent) MutateLength(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *StreamNotificationEvent) Data(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *StreamNotificationEvent) DataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *StreamNotificationEvent) DataBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StreamNotificationEvent) MutateData(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *StreamNotificationEvent) ErrorMsg() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func StreamNotificationEventStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func StreamNotificationEventAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func StreamNotificationEventAddType(builder *flatbuffers.Builder, type_ NotificationEventType) {
	builder.PrependByteSlot(1, byte(type_), 0)
}
func StreamNotificationEventAddLength(builder *flatbuffers.Builder, length int32) {
	builder.PrependInt32Slot(2, length, 0)
}
func StreamNotificationEventAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(data), 0)
}
func StreamNotificationEventStartDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func StreamNotificationEventAddErrorMsg(builder *flatbuffers.Builder, errorMsg flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(errorMsg), 0)
}
func StreamNotificationEventEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
