// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package stream

import "strconv"

type StreamControlOps uint32

const (
	StreamControlOpsNew   StreamControlOps = 0
	StreamControlOpsClose StreamControlOps = 1
)

var EnumNamesStreamControlOps = map[StreamControlOps]string{
	StreamControlOpsNew:   "New",
	StreamControlOpsClose: "Close",
}

var EnumValuesStreamControlOps = map[string]StreamControlOps{
	"New":   StreamControlOpsNew,
	"Close": StreamControlOpsClose,
}

func (v StreamControlOps) String() string {
	if s, ok := EnumNamesStreamControlOps[v]; ok {
		return s
	}
	return "StreamControlOps(" + strconv.FormatInt(int64(v), 10) + ")"
}
