// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package stream

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StreamData struct {
	_tab flatbuffers.Table
}

func GetRootAsStreamData(buf []byte, offset flatbuffers.UOffsetT) *StreamData {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StreamData{}
	x.Init(buf, n+offset)
	return x
}

func FinishStreamDataBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStreamData(buf []byte, offset flatbuffers.UOffsetT) *StreamData {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StreamData{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStreamDataBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StreamData) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StreamData) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StreamData) StreamId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return -1
}

func (rcv *StreamData) MutateStreamId(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *StreamData) Sequence() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return -1
}

func (rcv *StreamData) MutateSequence(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *StreamData) RequestId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return -1
}

func (rcv *StreamData) MutateRequestId(n int64) bool {
	return rcv._tab.MutateInt64Slot(8, n)
}

func (rcv *StreamData) IsReply() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *StreamData) MutateIsReply(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

func (rcv *StreamData) DataType() StreamDataWrapper {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return StreamDataWrapper(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *StreamData) MutateDataType(n StreamDataWrapper) bool {
	return rcv._tab.MutateByteSlot(12, byte(n))
}

func (rcv *StreamData) Data(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func (rcv *StreamData) Final() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *StreamData) MutateFinal(n bool) bool {
	return rcv._tab.MutateBoolSlot(16, n)
}

func StreamDataStart(builder *flatbuffers.Builder) {
	builder.StartObject(7)
}
func StreamDataAddStreamId(builder *flatbuffers.Builder, streamId int32) {
	builder.PrependInt32Slot(0, streamId, -1)
}
func StreamDataAddSequence(builder *flatbuffers.Builder, sequence int64) {
	builder.PrependInt64Slot(1, sequence, -1)
}
func StreamDataAddRequestId(builder *flatbuffers.Builder, requestId int64) {
	builder.PrependInt64Slot(2, requestId, -1)
}
func StreamDataAddIsReply(builder *flatbuffers.Builder, isReply bool) {
	builder.PrependBoolSlot(3, isReply, false)
}
func StreamDataAddDataType(builder *flatbuffers.Builder, dataType StreamDataWrapper) {
	builder.PrependByteSlot(4, byte(dataType), 0)
}
func StreamDataAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(data), 0)
}
func StreamDataAddFinal(builder *flatbuffers.Builder, final bool) {
	builder.PrependBoolSlot(6, final, false)
}
func StreamDataEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
