// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package stream

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StreamControlResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsStreamControlResponse(buf []byte, offset flatbuffers.UOffsetT) *StreamControlResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StreamControlResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishStreamControlResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStreamControlResponse(buf []byte, offset flatbuffers.UOffsetT) *StreamControlResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StreamControlResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStreamControlResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StreamControlResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StreamControlResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StreamControlResponse) RequestId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return -1
}

func (rcv *StreamControlResponse) MutateRequestId(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *StreamControlResponse) StreamId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return -1
}

func (rcv *StreamControlResponse) MutateStreamId(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func StreamControlResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func StreamControlResponseAddRequestId(builder *flatbuffers.Builder, requestId int32) {
	builder.PrependInt32Slot(0, requestId, -1)
}
func StreamControlResponseAddStreamId(builder *flatbuffers.Builder, streamId int32) {
	builder.PrependInt32Slot(1, streamId, -1)
}
func StreamControlResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
