// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package stream

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StreamOperationEvent struct {
	_tab flatbuffers.Table
}

func GetRootAsStreamOperationEvent(buf []byte, offset flatbuffers.UOffsetT) *StreamOperationEvent {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StreamOperationEvent{}
	x.Init(buf, n+offset)
	return x
}

func FinishStreamOperationEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStreamOperationEvent(buf []byte, offset flatbuffers.UOffsetT) *StreamOperationEvent {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StreamOperationEvent{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStreamOperationEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StreamOperationEvent) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StreamOperationEvent) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StreamOperationEvent) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StreamOperationEvent) Op() OperationType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return OperationType(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *StreamOperationEvent) MutateOp(n OperationType) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *StreamOperationEvent) Length() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StreamOperationEvent) MutateLength(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *StreamOperationEvent) Data(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *StreamOperationEvent) DataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *StreamOperationEvent) DataBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StreamOperationEvent) MutateData(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func StreamOperationEventStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func StreamOperationEventAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func StreamOperationEventAddOp(builder *flatbuffers.Builder, op OperationType) {
	builder.PrependByteSlot(1, byte(op), 0)
}
func StreamOperationEventAddLength(builder *flatbuffers.Builder, length int32) {
	builder.PrependInt32Slot(2, length, 0)
}
func StreamOperationEventAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(data), 0)
}
func StreamOperationEventStartDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func StreamOperationEventEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
