// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package stream

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StreamControlRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsStreamControlRequest(buf []byte, offset flatbuffers.UOffsetT) *StreamControlRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StreamControlRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishStreamControlRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStreamControlRequest(buf []byte, offset flatbuffers.UOffsetT) *StreamControlRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StreamControlRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStreamControlRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StreamControlRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StreamControlRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StreamControlRequest) RequestId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return -1
}

func (rcv *StreamControlRequest) MutateRequestId(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *StreamControlRequest) ClassName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StreamControlRequest) Op() StreamControlOps {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return StreamControlOps(rcv._tab.GetUint32(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *StreamControlRequest) MutateOp(n StreamControlOps) bool {
	return rcv._tab.MutateUint32Slot(8, uint32(n))
}

func (rcv *StreamControlRequest) StreamId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return -1
}

func (rcv *StreamControlRequest) MutateStreamId(n int32) bool {
	return rcv._tab.MutateInt32Slot(10, n)
}

func StreamControlRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func StreamControlRequestAddRequestId(builder *flatbuffers.Builder, requestId int32) {
	builder.PrependInt32Slot(0, requestId, -1)
}
func StreamControlRequestAddClassName(builder *flatbuffers.Builder, className flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(className), 0)
}
func StreamControlRequestAddOp(builder *flatbuffers.Builder, op StreamControlOps) {
	builder.PrependUint32Slot(2, uint32(op), 0)
}
func StreamControlRequestAddStreamId(builder *flatbuffers.Builder, streamId int32) {
	builder.PrependInt32Slot(3, streamId, -1)
}
func StreamControlRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
