// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package stream

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StreamRawData struct {
	_tab flatbuffers.Table
}

func GetRootAsStreamRawData(buf []byte, offset flatbuffers.UOffsetT) *StreamRawData {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StreamRawData{}
	x.Init(buf, n+offset)
	return x
}

func FinishStreamRawDataBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStreamRawData(buf []byte, offset flatbuffers.UOffsetT) *StreamRawData {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StreamRawData{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStreamRawDataBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StreamRawData) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StreamRawData) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StreamRawData) Length() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StreamRawData) MutateLength(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *StreamRawData) Data(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *StreamRawData) DataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *StreamRawData) DataBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StreamRawData) MutateData(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func StreamRawDataStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func StreamRawDataAddLength(builder *flatbuffers.Builder, length int32) {
	builder.PrependInt32Slot(0, length, 0)
}
func StreamRawDataAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(data), 0)
}
func StreamRawDataStartDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func StreamRawDataEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
