// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package io

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type InputRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsInputRequest(buf []byte, offset flatbuffers.UOffsetT) *InputRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &InputRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishInputRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsInputRequest(buf []byte, offset flatbuffers.UOffsetT) *InputRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &InputRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedInputRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *InputRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *InputRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *InputRequest) Prompt() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *InputRequest) Dryrun() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *InputRequest) MutateDryrun(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func InputRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func InputRequestAddPrompt(builder *flatbuffers.Builder, prompt flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(prompt), 0)
}
func InputRequestAddDryrun(builder *flatbuffers.Builder, dryrun bool) {
	builder.PrependBoolSlot(1, dryrun, false)
}
func InputRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
