// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package io

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type InputResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsInputResponse(buf []byte, offset flatbuffers.UOffsetT) *InputResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &InputResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishInputResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsInputResponse(buf []byte, offset flatbuffers.UOffsetT) *InputResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &InputResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedInputResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *InputResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *InputResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *InputResponse) Text() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func InputResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func InputResponseAddText(builder *flatbuffers.Builder, text flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(text), 0)
}
func InputResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
