// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package io

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RecordRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsRecordRequest(buf []byte, offset flatbuffers.UOffsetT) *RecordRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RecordRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishRecordRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRecordRequest(buf []byte, offset flatbuffers.UOffsetT) *RecordRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RecordRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRecordRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RecordRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RecordRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RecordRequest) Prompt() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RecordRequest) Model() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RecordRequest) Dryrun() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *RecordRequest) MutateDryrun(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func RecordRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func RecordRequestAddPrompt(builder *flatbuffers.Builder, prompt flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(prompt), 0)
}
func RecordRequestAddModel(builder *flatbuffers.Builder, model flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(model), 0)
}
func RecordRequestAddDryrun(builder *flatbuffers.Builder, dryrun bool) {
	builder.PrependBoolSlot(2, dryrun, false)
}
func RecordRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
