// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package io

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RecordResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsRecordResponse(buf []byte, offset flatbuffers.UOffsetT) *RecordResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RecordResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishRecordResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRecordResponse(buf []byte, offset flatbuffers.UOffsetT) *RecordResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RecordResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRecordResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RecordResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RecordResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RecordResponse) Text() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func RecordResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func RecordResponseAddText(builder *flatbuffers.Builder, text flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(text), 0)
}
func RecordResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
