// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package io

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SpeakRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsSpeakRequest(buf []byte, offset flatbuffers.UOffsetT) *SpeakRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SpeakRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishSpeakRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSpeakRequest(buf []byte, offset flatbuffers.UOffsetT) *SpeakRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SpeakRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSpeakRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SpeakRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SpeakRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SpeakRequest) Text() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SpeakRequest) Model() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SpeakRequest) Voice() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SpeakRequest) Format() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SpeakRequest) Dryrun() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *SpeakRequest) MutateDryrun(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

func SpeakRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func SpeakRequestAddText(builder *flatbuffers.Builder, text flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(text), 0)
}
func SpeakRequestAddModel(builder *flatbuffers.Builder, model flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(model), 0)
}
func SpeakRequestAddVoice(builder *flatbuffers.Builder, voice flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(voice), 0)
}
func SpeakRequestAddFormat(builder *flatbuffers.Builder, format flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(format), 0)
}
func SpeakRequestAddDryrun(builder *flatbuffers.Builder, dryrun bool) {
	builder.PrependBoolSlot(4, dryrun, false)
}
func SpeakRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
