// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package io

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SpeakResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsSpeakResponse(buf []byte, offset flatbuffers.UOffsetT) *SpeakResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SpeakResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishSpeakResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSpeakResponse(buf []byte, offset flatbuffers.UOffsetT) *SpeakResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SpeakResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSpeakResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SpeakResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SpeakResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SpeakResponse) Data() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func SpeakResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SpeakResponseAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(data), 0)
}
func SpeakResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
