// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package custom

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CustomRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsCustomRequest(buf []byte, offset flatbuffers.UOffsetT) *CustomRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CustomRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishCustomRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCustomRequest(buf []byte, offset flatbuffers.UOffsetT) *CustomRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CustomRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCustomRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CustomRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CustomRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CustomRequest) MethodStr() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *CustomRequest) RequestInfoType() RequestInfo {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return RequestInfo(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *CustomRequest) MutateRequestInfoType(n RequestInfo) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *CustomRequest) RequestInfo(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func CustomRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func CustomRequestAddMethodStr(builder *flatbuffers.Builder, methodStr flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(methodStr), 0)
}
func CustomRequestAddRequestInfoType(builder *flatbuffers.Builder, requestInfoType RequestInfo) {
	builder.PrependByteSlot(1, byte(requestInfoType), 0)
}
func CustomRequestAddRequestInfo(builder *flatbuffers.Builder, requestInfo flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(requestInfo), 0)
}
func CustomRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
