// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package custom

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type NormalRequestInfo struct {
	_tab flatbuffers.Table
}

func GetRootAsNormalRequestInfo(buf []byte, offset flatbuffers.UOffsetT) *NormalRequestInfo {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &NormalRequestInfo{}
	x.Init(buf, n+offset)
	return x
}

func FinishNormalRequestInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsNormalRequestInfo(buf []byte, offset flatbuffers.UOffsetT) *NormalRequestInfo {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &NormalRequestInfo{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedNormalRequestInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *NormalRequestInfo) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *NormalRequestInfo) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *NormalRequestInfo) ParamsStr() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func NormalRequestInfoStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func NormalRequestInfoAddParamsStr(builder *flatbuffers.Builder, paramsStr flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(paramsStr), 0)
}
func NormalRequestInfoEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
