// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package custom

import "strconv"

type RequestInfo byte

const (
	RequestInfoNONE              RequestInfo = 0
	RequestInfoNormalRequestInfo RequestInfo = 1
)

var EnumNamesRequestInfo = map[RequestInfo]string{
	RequestInfoNONE:              "NONE",
	RequestInfoNormalRequestInfo: "NormalRequestInfo",
}

var EnumValuesRequestInfo = map[string]RequestInfo{
	"NONE":              RequestInfoNONE,
	"NormalRequestInfo": RequestInfoNormalRequestInfo,
}

func (v RequestInfo) String() string {
	if s, ok := EnumNamesRequestInfo[v]; ok {
		return s
	}
	return "RequestInfo(" + strconv.FormatInt(int64(v), 10) + ")"
}
