// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package transport

import "strconv"

type Method uint32

const (
	MethodUnknown            Method = 0
	MethodTransform          Method = 1
	MethodInput              Method = 2
	MethodSpeak              Method = 3
	MethodRecord             Method = 4
	MethodToolInvoke         Method = 5
	MethodInternalToolCreate Method = 6
	MethodVecStoreCreate     Method = 7
	MethodVecStoreInsert     Method = 8
	MethodVecStoreQuery      Method = 9
	MethodVecStoreDelete     Method = 10
	MethodCustom             Method = 11
	MethodStreamCtrl         Method = 12
)

var EnumNamesMethod = map[Method]string{
	MethodUnknown:            "Unknown",
	MethodTransform:          "Transform",
	MethodInput:              "Input",
	MethodSpeak:              "Speak",
	MethodRecord:             "Record",
	MethodToolInvoke:         "ToolInvoke",
	MethodInternalToolCreate: "InternalToolCreate",
	MethodVecStoreCreate:     "VecStoreCreate",
	MethodVecStoreInsert:     "VecStoreInsert",
	MethodVecStoreQuery:      "VecStoreQuery",
	MethodVecStoreDelete:     "VecStoreDelete",
	MethodCustom:             "Custom",
	MethodStreamCtrl:         "StreamCtrl",
}

var EnumValuesMethod = map[string]Method{
	"Unknown":            MethodUnknown,
	"Transform":          MethodTransform,
	"Input":              MethodInput,
	"Speak":              MethodSpeak,
	"Record":             MethodRecord,
	"ToolInvoke":         MethodToolInvoke,
	"InternalToolCreate": MethodInternalToolCreate,
	"VecStoreCreate":     MethodVecStoreCreate,
	"VecStoreInsert":     MethodVecStoreInsert,
	"VecStoreQuery":      MethodVecStoreQuery,
	"VecStoreDelete":     MethodVecStoreDelete,
	"Custom":             MethodCustom,
	"StreamCtrl":         MethodStreamCtrl,
}

func (v Method) String() string {
	if s, ok := EnumNamesMethod[v]; ok {
		return s
	}
	return "Method(" + strconv.FormatInt(int64(v), 10) + ")"
}
