// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package transport

import "strconv"

type Signal uint32

const (
	SignalUnknown    Signal = 0
	SignalTerminate  Signal = 1
	SignalStreamData Signal = 2
)

var EnumNamesSignal = map[Signal]string{
	SignalUnknown:    "Unknown",
	SignalTerminate:  "Terminate",
	SignalStreamData: "StreamData",
}

var EnumValuesSignal = map[string]Signal{
	"Unknown":    SignalUnknown,
	"Terminate":  SignalTerminate,
	"StreamData": SignalStreamData,
}

func (v Signal) String() string {
	if s, ok := EnumNamesSignal[v]; ok {
		return s
	}
	return "Signal(" + strconv.FormatInt(int64(v), 10) + ")"
}
