// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package transport

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TransportSignal struct {
	_tab flatbuffers.Table
}

func GetRootAsTransportSignal(buf []byte, offset flatbuffers.UOffsetT) *TransportSignal {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TransportSignal{}
	x.Init(buf, n+offset)
	return x
}

func FinishTransportSignalBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTransportSignal(buf []byte, offset flatbuffers.UOffsetT) *TransportSignal {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TransportSignal{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTransportSignalBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TransportSignal) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TransportSignal) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TransportSignal) Method() Signal {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return Signal(rcv._tab.GetUint32(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *TransportSignal) MutateMethod(n Signal) bool {
	return rcv._tab.MutateUint32Slot(4, uint32(n))
}

func (rcv *TransportSignal) Payload(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *TransportSignal) PayloadLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *TransportSignal) PayloadBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TransportSignal) MutatePayload(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func TransportSignalStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func TransportSignalAddMethod(builder *flatbuffers.Builder, method Signal) {
	builder.PrependUint32Slot(0, uint32(method), 0)
}
func TransportSignalAddPayload(builder *flatbuffers.Builder, payload flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(payload), 0)
}
func TransportSignalStartPayloadVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func TransportSignalEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
