// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package transport

import "strconv"

type TransportMessageRaw_Data byte

const (
	TransportMessageRaw_DataNONE              TransportMessageRaw_Data = 0
	TransportMessageRaw_DataTransportRequest  TransportMessageRaw_Data = 1
	TransportMessageRaw_DataTransportResponse TransportMessageRaw_Data = 2
	TransportMessageRaw_DataTransportSignal   TransportMessageRaw_Data = 3
)

var EnumNamesTransportMessageRaw_Data = map[TransportMessageRaw_Data]string{
	TransportMessageRaw_DataNONE:              "NONE",
	TransportMessageRaw_DataTransportRequest:  "TransportRequest",
	TransportMessageRaw_DataTransportResponse: "TransportResponse",
	TransportMessageRaw_DataTransportSignal:   "TransportSignal",
}

var EnumValuesTransportMessageRaw_Data = map[string]TransportMessageRaw_Data{
	"NONE":              TransportMessageRaw_DataNONE,
	"TransportRequest":  TransportMessageRaw_DataTransportRequest,
	"TransportResponse": TransportMessageRaw_DataTransportResponse,
	"TransportSignal":   TransportMessageRaw_DataTransportSignal,
}

func (v TransportMessageRaw_Data) String() string {
	if s, ok := EnumNamesTransportMessageRaw_Data[v]; ok {
		return s
	}
	return "TransportMessageRaw_Data(" + strconv.FormatInt(int64(v), 10) + ")"
}
