// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package transport

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TransportMessageRaw struct {
	_tab flatbuffers.Table
}

func GetRootAsTransportMessageRaw(buf []byte, offset flatbuffers.UOffsetT) *TransportMessageRaw {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TransportMessageRaw{}
	x.Init(buf, n+offset)
	return x
}

func FinishTransportMessageRawBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTransportMessageRaw(buf []byte, offset flatbuffers.UOffsetT) *TransportMessageRaw {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TransportMessageRaw{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTransportMessageRawBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TransportMessageRaw) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TransportMessageRaw) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TransportMessageRaw) DataType() TransportMessageRaw_Data {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return TransportMessageRaw_Data(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *TransportMessageRaw) MutateDataType(n TransportMessageRaw_Data) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *TransportMessageRaw) Data(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func TransportMessageRawStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func TransportMessageRawAddDataType(builder *flatbuffers.Builder, dataType TransportMessageRaw_Data) {
	builder.PrependByteSlot(0, byte(dataType), 0)
}
func TransportMessageRawAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(data), 0)
}
func TransportMessageRawEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
