// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package speech

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ASRResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsASRResponse(buf []byte, offset flatbuffers.UOffsetT) *ASRResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ASRResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishASRResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsASRResponse(buf []byte, offset flatbuffers.UOffsetT) *ASRResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ASRResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedASRResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ASRResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ASRResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ASRResponse) Text() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ASRResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ASRResponseAddText(builder *flatbuffers.Builder, text flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(text), 0)
}
func ASRResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
