// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package chat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ChatCompletionRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsChatCompletionRequest(buf []byte, offset flatbuffers.UOffsetT) *ChatCompletionRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ChatCompletionRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishChatCompletionRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsChatCompletionRequest(buf []byte, offset flatbuffers.UOffsetT) *ChatCompletionRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ChatCompletionRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedChatCompletionRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ChatCompletionRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ChatCompletionRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ChatCompletionRequest) Messages(obj *ChatMessage, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *ChatCompletionRequest) MessagesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ChatCompletionRequest) Model() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ChatCompletionRequest) Tools(obj *ToolInfo, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *ChatCompletionRequest) ToolsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ChatCompletionRequest) ReturnOnToolcall() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ChatCompletionRequest) MutateReturnOnToolcall(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

func ChatCompletionRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func ChatCompletionRequestAddMessages(builder *flatbuffers.Builder, messages flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(messages), 0)
}
func ChatCompletionRequestStartMessagesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ChatCompletionRequestAddModel(builder *flatbuffers.Builder, model flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(model), 0)
}
func ChatCompletionRequestAddTools(builder *flatbuffers.Builder, tools flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(tools), 0)
}
func ChatCompletionRequestStartToolsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ChatCompletionRequestAddReturnOnToolcall(builder *flatbuffers.Builder, returnOnToolcall bool) {
	builder.PrependBoolSlot(3, returnOnToolcall, false)
}
func ChatCompletionRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
