// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package chat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ChatMetadata struct {
	_tab flatbuffers.Table
}

func GetRootAsChatMetadata(buf []byte, offset flatbuffers.UOffsetT) *ChatMetadata {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ChatMetadata{}
	x.Init(buf, n+offset)
	return x
}

func FinishChatMetadataBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsChatMetadata(buf []byte, offset flatbuffers.UOffsetT) *ChatMetadata {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ChatMetadata{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedChatMetadataBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ChatMetadata) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ChatMetadata) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ChatMetadata) Role() Role {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return Role(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ChatMetadata) MutateRole(n Role) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func (rcv *ChatMetadata) Reason() Reason {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return Reason(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ChatMetadata) MutateReason(n Reason) bool {
	return rcv._tab.MutateInt8Slot(6, int8(n))
}

func ChatMetadataStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ChatMetadataAddRole(builder *flatbuffers.Builder, role Role) {
	builder.PrependInt8Slot(0, int8(role), 0)
}
func ChatMetadataAddReason(builder *flatbuffers.Builder, reason Reason) {
	builder.PrependInt8Slot(1, int8(reason), 0)
}
func ChatMetadataEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
