// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package chat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ChatCompletionResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsChatCompletionResponse(buf []byte, offset flatbuffers.UOffsetT) *ChatCompletionResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ChatCompletionResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishChatCompletionResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsChatCompletionResponse(buf []byte, offset flatbuffers.UOffsetT) *ChatCompletionResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ChatCompletionResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedChatCompletionResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ChatCompletionResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ChatCompletionResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ChatCompletionResponse) Code() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ChatCompletionResponse) MutateCode(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *ChatCompletionResponse) Error() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ChatCompletionResponse) Messages(obj *ChatMessage, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *ChatCompletionResponse) MessagesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func ChatCompletionResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func ChatCompletionResponseAddCode(builder *flatbuffers.Builder, code int32) {
	builder.PrependInt32Slot(0, code, 0)
}
func ChatCompletionResponseAddError(builder *flatbuffers.Builder, error flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(error), 0)
}
func ChatCompletionResponseAddMessages(builder *flatbuffers.Builder, messages flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(messages), 0)
}
func ChatCompletionResponseStartMessagesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ChatCompletionResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
