// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package chat

import "strconv"

type Reason int8

const (
	ReasonToolCalls Reason = 0
	ReasonLength    Reason = 1
	ReasonStop      Reason = 2
	ReasonOther     Reason = 3
)

var EnumNamesReason = map[Reason]string{
	ReasonToolCalls: "ToolCalls",
	ReasonLength:    "Length",
	ReasonStop:      "Stop",
	ReasonOther:     "Other",
}

var EnumValuesReason = map[string]Reason{
	"ToolCalls": ReasonToolCalls,
	"Length":    ReasonLength,
	"Stop":      ReasonStop,
	"Other":     ReasonOther,
}

func (v Reason) String() string {
	if s, ok := EnumNamesReason[v]; ok {
		return s
	}
	return "Reason(" + strconv.FormatInt(int64(v), 10) + ")"
}
