// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package chat

import "strconv"

type Role int8

const (
	RoleSystem    Role = 0
	RoleUser      Role = 1
	RoleAssistant Role = 2
	RoleDeveloper Role = 3
	RoleTool      Role = 4
	RoleOther     Role = 5
)

var EnumNamesRole = map[Role]string{
	RoleSystem:    "System",
	RoleUser:      "User",
	RoleAssistant: "Assistant",
	RoleDeveloper: "Developer",
	RoleTool:      "Tool",
	RoleOther:     "Other",
}

var EnumValuesRole = map[string]Role{
	"System":    RoleSystem,
	"User":      RoleUser,
	"Assistant": RoleAssistant,
	"Developer": RoleDeveloper,
	"Tool":      RoleTool,
	"Other":     RoleOther,
}

func (v Role) String() string {
	if s, ok := EnumNamesRole[v]; ok {
		return s
	}
	return "Role(" + strconv.FormatInt(int64(v), 10) + ")"
}
