// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package chat

import (
	flatbuffers "github.com/google/flatbuffers/go"

	spear__proto__tool "github.com/lfedgeai/spear/pkg/spear/proto/tool"
)

type ToolInfo struct {
	_tab flatbuffers.Table
}

func GetRootAsToolInfo(buf []byte, offset flatbuffers.UOffsetT) *ToolInfo {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ToolInfo{}
	x.Init(buf, n+offset)
	return x
}

func FinishToolInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsToolInfo(buf []byte, offset flatbuffers.UOffsetT) *ToolInfo {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ToolInfo{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedToolInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ToolInfo) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ToolInfo) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ToolInfo) DataType() spear__proto__tool.ToolInfo {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return spear__proto__tool.ToolInfo(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ToolInfo) MutateDataType(n spear__proto__tool.ToolInfo) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *ToolInfo) Data(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func ToolInfoStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ToolInfoAddDataType(builder *flatbuffers.Builder, dataType spear__proto__tool.ToolInfo) {
	builder.PrependByteSlot(0, byte(dataType), 0)
}
func ToolInfoAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(data), 0)
}
func ToolInfoEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
